language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  # - "pypy" - won't work as smmap doesn't work (see smmap/.travis.yml for details)

git:
  # a higher depth is needed for one of the tests - lets fet
  depth: 1000
install:
  - pip install coveralls
script: 
  - ulimit -n 48
  - ulimit -n
  - nosetests -v --with-coverage
after_success:
  - coveralls

