language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  # - "pypy" - won't work as smmap doesn't work (see smmap/.travis.yml for details)

git:
  # a higher depth is needed for one of the tests - lets fet
  depth: 1000
install:
  - pip install coveralls
    
    ## Install any dev-requirements (FIXME: remove on release)
  - pip install -I git+https://github.com/ankostis/smmap.git@v2.1.0.dev1
  - pip install -r requirements.txt
script: 
  - ulimit -n 48
  - ulimit -n
  - nosetests -v --with-coverage
after_success:
  - coveralls

